name: "Repo Public Readiness Scanner"
description: "Scan a repository for secrets, quality issues, missing docs, and compliance problems before going public"
author: "PSDN-AI"

inputs:
  repo_path:
    description: "Path to the repository to scan (defaults to current workspace)"
    required: false
    default: "."

outputs:
  status:
    description: "Overall scan status: READY, NEEDS_WORK, or NOT_READY"
    value: ${{ steps.scan.outputs.status }}
  report:
    description: "Path to the generated Markdown report"
    value: ${{ steps.scan.outputs.report }}

runs:
  using: "composite"
  steps:
    - name: Run scanner
      id: scan
      shell: bash
      run: |
        REPORT_PATH="${{ runner.temp }}/readiness-report.md"
        "${{ github.action_path }}/scanner/run_scan.sh" "${{ inputs.repo_path }}" > "$REPORT_PATH"

        # Extract overall status for output
        if grep -q "❌ NOT READY" "$REPORT_PATH"; then
          echo "status=NOT_READY" >> "$GITHUB_OUTPUT"
        elif grep -q "⚠️ NEEDS WORK" "$REPORT_PATH"; then
          echo "status=NEEDS_WORK" >> "$GITHUB_OUTPUT"
        else
          echo "status=READY" >> "$GITHUB_OUTPUT"
        fi

        echo "report=$REPORT_PATH" >> "$GITHUB_OUTPUT"

    - name: Display report
      shell: bash
      run: |
        echo "## Repo Public Readiness Report" >> "$GITHUB_STEP_SUMMARY"
        cat "${{ steps.scan.outputs.report }}" >> "$GITHUB_STEP_SUMMARY"
